### ISSUE TITLE
Provided Value for Enable Spawns could not be parsed

### ISSUE THREAD

**Issue by kadonboiz** [MeridiusIX/Modular-Encounters-Systems#101]
After trying ``/MES.Settings.PlanetaryCargoShips.EnableSpawns.Value`` I dont know what to put as its value, I tried 1 and 0, True and False, T and F with no luck, any help would be appriciated.

**Comment by bodyboarder2528** [comment]
all lower case true

**Comment by bodyboarder2528** [comment]
if its a true or false command then it must be lowercase for them

**Comment by MeridiusIX** [comment]
Fix for this should now be live
