### ISSUE TITLE
NPC Economy stations being removed?

### ISSUE THREAD

**Issue by MdBourg98** [MeridiusIX/Modular-Encounters-Systems#104]
Looks like MES is despawning my stations? 

Console:
11:07:49.7921 [INFO]   Keen: MES Spawner / CleanUp: UVCS OrbitalStation 913539423572039759 Grid is being Closed.
11:07:49.7921 [INFO]   Keen: MES Spawner / CleanUp:  - Despawn Source: [CleanUp-Distance]
11:07:49.7921 [INFO]   Keen: MES Spawner / CleanUp:  - Grid Majority Owner [144115188075855936]. NPC Ownership: True"

Happened to all 11 stations found in a new server as I approached them, 9 of the 11 were from respawn ship datapads, The other 2 were found randomly.

**Comment by MeridiusIX** [comment]
That shouldn't be happening. I'll look into it.
