### ISSUE TITLE
MES API CustomSpawnRequest always spawns to zero point regardless of parameters

### ISSUE THREAD

**Issue by remcomulder** [MeridiusIX/Modular-Encounters-Systems#164]
When attempting to spawn any group using the CustomSpawnRequest, MES will spawn the group at 0,0,0 instead of the supplied coordinates.

Observed inside the log:
2022-02-12 21:27:58.685 - Thread:   1 ->  MES:Pathing: Relative Spawn Coordinates:   X:-62183.2856246119 Y:13902.2051558873 Z:-7645.97853846589
2022-02-12 21:27:58.685 - Thread:   1 ->  MES:Pathing: Final Prefab Coordinates:     X:-Infinity Y:Infinity Z:-Infinity

On tracing through the code, it appears that pathing system called by SpawnRequest.CalculateSpawn relies on the spawnMatrix parameter which is always set to zero when called by the API facade.

A suggestion might be to have a fallback that uses the coords parameter when spawnMatrix is zero, or perhaps update PrefabSpawner.SpawnPrefab so that it will use npcData.StartCoords when spawnMatrix.Translation is zero, as this way prefabs can always be spawned even when pathing data isn't relevant.

**Comment by MeridiusIX** [comment]
I'm not seeing the breakdown in the code for this. So far I see `MESApi` takes the provided `spawnMatrix`, then passes it through `LocalApi` to `SpawnRequest.CalculateSpawn`. As long as a value is provided, it should not be defaulting to 0,0,0. The rest appears to be ok as well as it goes down to the pathing methods.

If you have any more info on how you're getting that result, I'd love to hear it.

**Comment by MeridiusIX** [comment]
Fixed in current version
