### ISSUE TITLE
incorrect setting for description

### ISSUE THREAD

**Issue by Windessy** [MeridiusIX/Modular-Encounters-Systems#187]
in  https://github.com/MeridiusIX/Modular-Encounters-Systems/wiki/Admin-&-Configuration:-General-Settings
you have SpawnedVoxelCheckTimerTrigger two times in a row. 
The second one must be SpawnedVoxelMinimumGridDistance according to description.

**Comment by MeridiusIX** [comment]
Thanks, got it fixed.
