### ISSUE TITLE
Random Encounter / Planetary Installation Exclusion Zones

### ISSUE THREAD

**Issue by MeridiusIX** [MeridiusIX/Modular-Encounters-Systems#188]
An old feature from Planetary Installations stand-alone mod. Allow these encounters to create an exclusion zone upon spawn that would prevent other encounters of the same type to spawn within that zone, even if the encounter has been removed / destroyed / captured / etc.

This would encourage actual exploration / expansion since NPCs would eventually not be able to spawn in a player area after too many spawns

Before y'all get your undies in a twist, yes this will be an optional mode - although will be enabled by default.

**Comment by TheFinalEvent97** [comment]
Hmm, so basically the RemoteControlCode restrictions but applying to everything and even after it's gone? Plus having it enabled by default is a good way to have even more confused people complaining :p
