### ISSUE TITLE
Energy Weapon Framework

### ISSUE THREAD

**Issue by MeridiusIX** [MeridiusIX/Modular-Encounters-Systems#189]
Lucas: Look, I need the beam weapons to make Tesla Drone and Vengeance Drone work in MES

Meridius_IX: This doesn't seem like something that would fit in the scope of MES though.

Lucas: It's ok if only the NPCs get to use it, we can be careful about implementation. Heck, I already wrote the code for it once!

Meridius_IX: No, "I" wrote the code for it once. Remember the Custom Energy Weapon framework

Lucas: Oh right, I remember that. The code you ripped out of the Corruption mod? THAT Custom Energy Weapon framework??

Meridius_IX: ..........

Lucas: ...... Just gimme my lasers.

**Comment by black-tortoise-official** [comment]
We, the community of NPC modders, want an Energy Weapon Framework! :-D
