### ISSUE TITLE
Config Presets

### ISSUE THREAD

**Issue by MeridiusIX** [MeridiusIX/Modular-Encounters-Systems#223]
I want to create a number of config presets that people can easily activate.

These will set all settings to certain values so configs can be better tuned for certain gameplay styles.

I plan to consult with server admins to gauge what they use for settings in varying populations, and what single player and smaller groups use as well

**Comment by TheFinalEvent97** [comment]
Could also have these as opt-in spawn conditions, so mods could be tailored to specific presets.
