### ISSUE TITLE
DisposableBeaconLogic.Setup never calls the base function BaseBlockLogic.Setup, so Active is always false so it early outs in the Update

### ISSUE THREAD

**Issue by keleios** [MeridiusIX/Modular-Encounters-Systems#239]
https://github.com/MeridiusIX/Modular-Encounters-Systems/blob/e184e4d5a95ad47c7c9fb450ee4c79cc7c3444b1/Data/Scripts/ModularEncountersSystems/BlockLogic/DisposableBeaconLogic.cs#L29

The update in DisposableBeaconLogic never executes as "Active" is always false.

**Comment by MeridiusIX** [comment]
Fixed
