### ISSUE TITLE
Get Active NPCs command only lists grids, not creatures

### ISSUE THREAD

**Issue by Derpford** [MeridiusIX/Modular-Encounters-Systems#245]
I've been trying to figure out how to turn wolves off for a couple hours now. Unfortunately, while I'm reasonably sure there's a way to blacklist *just* wolves...there does not appear to be a way to find out what the wolf entity's name is for adding to the blacklist. I figured the GetActiveNPCs command would show the wolves, but...no dice. It only shows grids!

**Comment by MeridiusIX** [comment]
You can use /MES.GESAP to get creature spawngroups.
