### ISSUE TITLE
MES CLEANUP :: Player-grids despawning at cleanup execution when connected (Unconfirmed origin)

### ISSUE THREAD

**Issue by Varaxian** [MeridiusIX/Modular-Encounters-Systems#251]
**Description**
Player-grids which are connected (Gear or Connector types) despawn along with the NPC when NPC cleanup is triggered.  

**Reproduction**
- Configure
- Using a player-owned grid with less PCU than the NPC grid, connect to an NPC grid by Landing Gear block type
- Await MES NPC cleanup trigger
- Player-owned grid despawns at trigger execution

**Other Variables & Conditions**
- Allow supergridding = False
- Use-case: Dedicated Server (Torch)

**TORCH-related identifications**
- !fixship fails when connected to the larger NPC grid due to "You do not own the grid", supporting the possibility the MES NPC cleanup trigger being Secondary to a non-MES Primary origin of issue.

**Additional comments**
Reproduction variables are not 100% identified or validated, as this is currently a "Logical suspicion" due to the related events occurring at MES NPC cleanup trigger execution, when a Player-grid is connected to a larger NPC grid.

**Comment by Varaxian** [comment]
**Possibly related to Cleaning.cs @ 143**
`				//Unowned Filtering
				if (!config.CleanupIncludeUnowned) {

					if (grid.Ownership.HasFlag(GridOwnershipEnum.NpcMajority) || grid.Ownership.HasFlag(GridOwnershipEnum.NpcMinority)) {

						continue;
					
					}
				
				}
`

**Comment by MeridiusIX** [comment]
The cleanup processes have been overhauled as of 2.69.4, and these issues should be resolved
