### ISSUE TITLE
/MES.GESAP doesn't show gravity cargo ships

### ISSUE THREAD

**Issue by chuckination** [MeridiusIX/Modular-Encounters-Systems#252]
Noticed this working on gravity cargo ships, but /MES.GESAP doesn't list eligible gravity cargo ships when inside a planet's gravity deadzone without atmosphere but with gravity.  They will show as an atmosphere cargo ship spawn if you're down enough to be in atmosphere, though.

They do spawn with /MES.SPCS and the timed spawning produces the threats, but it just doesn't list in the diagnostics commands.

**Comment by MeridiusIX** [comment]
Addressed and fixed. Changes will be present in 2.69.4 update in approx 24-48 hrs
