### ISSUE TITLE
Feature Request: Admin and Configuration Commands for Combat Phase

### ISSUE THREAD

**Issue by SCBionicle** [MeridiusIX/Modular-Encounters-Systems#256]
Would it be possible to add in commands that could immediately start or end the combat phase? This would be helpful for balancing different npc spawn groups on a server or scenario.

**Comment by MeridiusIX** [comment]
/MES.Debug.ForceCombatPhase
/MES.Debug.ForcePeacePhase

Commands will be documented properly in the near-ish future
