### ISSUE TITLE
CleanupUnpoweredOverride is used even with powered grids

### ISSUE THREAD

**Issue by vmrob** [MeridiusIX/Modular-Encounters-Systems#259]
I was recently trying to figure out why despawns were happening when they shouldn't and it looks like a minor bug in the config.

Based on the docs, I think this needs some adjustment:

https://github.com/MeridiusIX/Modular-Encounters-Systems/blob/2ab63d213c762bddd38cbee12927535b35e11bc3/Data/Scripts/ModularEncountersSystems/Watchers/Cleaning.cs#L172-L176

Noting that `powered` is unused, I think the intention was instead...

```diff
 var player = PlayerManager.GetNearestPlayer(grid.GetPosition());
 var distance = player?.Distance(grid.GetPosition()) ?? 0;
 var powered = grid.IsPowered();
-var distanceTrigger = !config.CleanupUnpoweredOverride ? config.CleanupDistanceTrigger : config.CleanupUnpoweredDistanceTrigger;
+var distanceTrigger = (powered || !config.CleanupUnpoweredOverride) ? config.CleanupDistanceTrigger : config.CleanupUnpoweredDistanceTrigger;
 var timerTrigger = !config.CleanupUnpoweredOverride ? config.CleanupTimerTrigger : config.CleanupUnpoweredTimerTrigger;
```

**Comment by MeridiusIX** [comment]
Applied suggested fix, will be included in 2.69.5
