### ISSUE TITLE
Wrong condition in AddDefenseShieldsToGrid

### ISSUE THREAD

**Issue by michi84o** [MeridiusIX/Modular-Encounters-Systems#266]
In the NPCShieldManager class in the method AddDefenseShieldsToGrid() there is a condition that seems wrong.
```
SpawnLogger.Write("DSP: Check if Spawn Eligible", SpawnerDebugEnum.Manipulation);
if (!IsGlobalShieldProviderEnabled() && !spawnGroupAdd)
  return false;
```
The only call I found always sets spawnGroupAdd to 'true'. This means that the conditon in that if clause will always be false. Shouldn't there be an OR operator instead of AND?

**Comment by MeridiusIX** [comment]
Seems you're probably right with that, I'll fix in the next update.
