### ISSUE TITLE
Player ships attached to encounter subgrids get marked for cleanup and deleted

### ISSUE THREAD

**Issue by gaddi22** [MeridiusIX/Modular-Encounters-Systems#274]
During a ship battle I separated some parts from an encounter and I used landing gear to grab them for salvage. The parent grid eventually retreated while I was attached to that piece, and when it reached 3km away it deleted all my grids that were connected to the detached piece.

**Comment by MeridiusIX** [comment]
Next update will have some changes to address this (again). Let me know if it returns after that update later this weekend.
