### ISSUE TITLE
Player Grid Cleaned Up By MES

### ISSUE THREAD

**Issue by Prozon** [MeridiusIX/Modular-Encounters-Systems#278]
When the MES cleanup ran, it deleted a players ship. 

The setup for this was that they were in combat with an NPC, at some point they hit the NPC and maglocked to it. I believe this may be a similar issue to Issue #274, but in this scenario the player was not attached to the NPC when cleanup happened. They flew back to their base and had a Build and Repair welding the grid back up. The player logged out and waited for the grid to repair. Roughly 10 minutes after the repair was finished, the grid was deleted. The grid in question was "Baron Interceptor 007." 

**Keen Log:**
```11:23:26.8420 [INFO]   Keen: MES Spawner / CleanUp: Remaining Grids To Be Despawned: 2
11:23:26.8420 [INFO]   Keen: MES Spawner / CleanUp: Baron Interceptor 007 Grid is being Cleaned.
11:23:26.8420 [INFO]   Keen: MES Spawner / CleanUp:  - Despawn Source: Unknown
11:23:26.8420 [INFO]   Keen: MES Spawner / CleanUp:  - Baron Interceptor 007 Disconnecting Subgrids Before Cleanup
11:23:26.8420 [INFO]   Keen: MES Spawner / CleanUp:  - Disconnecting Parent From Other Subgrids Before Cleanup.
11:23:26.8420 [INFO]   Keen: MES Spawner / CleanUp:  - Baron Interceptor 007 Grid is Closed.
11:23:27.0085 [INFO]   Keen: MES Spawner / CleanUp: Remaining Grids To Be Despawned: 1
11:23:27.0085 [INFO]   Keen: MES Spawner / CleanUp: Large Grid 4718 Grid is being Cleaned.
11:23:27.0085 [INFO]   Keen: MES Spawner / CleanUp:  - Despawn Source: Unknown
11:23:27.0085 [INFO]   Keen: MES Spawner / CleanUp:  - Large Grid 4718 Disconnecting Subgrids Before Cleanup
11:23:27.0085 [INFO]   Keen: MES Spawner / CleanUp:  - Large Grid 4718 Grid is Closed.
```

**ALE Delete Tracker Log:**
`11:23:26.8580 [INFO]   Entity 126853342881220209   owned by player                     baronting [Off][AVT]      was closed! (Grid: Baron Interceptor 007)`

The Torch log did not register anything at this point. (It normally wouldn't for MES cleanups, but if anything else had cleaned it up, Torch would have logged it.)

If any more information arises, I will do my best to add to this. If you need anything from me, just let me know. I'm also **.prozon** on Discord if that is easier.

**Comment by MeridiusIX** [comment]
Next update will have some changes to address this (again). Let me know if it returns after that update later this weekend.
