### ISSUE TITLE
Play Sound At Spawn

### ISSUE THREAD

**Issue by MeridiusIX** [MeridiusIX/Modular-Encounters-Systems#36]
Ideas for this could include having a 'warp in' sound play for ships, or maybe a howl/scream for some creature/bot encounters.

**Comment by chipstix213** [comment]
If at all possible you could swap out the creatures attack noise.

**Comment by MeridiusIX** [comment]
> 
> 
> If at all possible you could swap out the creatures attack noise.

Those are brutally hard coded by the game. Would need to essentially create a framework that replaces them entirely and then set the definitions already in place to silent. Too much work for my taste : /
