### ISSUE TITLE
Create NPC Interior Turrets

### ISSUE THREAD

**Issue by MeridiusIX** [MeridiusIX/Modular-Encounters-Systems#44]
Since Keen nerfed the interior turret range to 400m, a special version of the turret should be added for NPC use that increases it back to 800m (many ships defense design assume they could use the 800m)

**Comment by TheFinalEvent97** [comment]
Apparently they nerfed the range of the ammo in the Warfare 1 update, they didn't update the turret UI to reflect this until the Heavy Industry update.
