### ISSUE TITLE
WeaponCore ranges not being set my manipulation tags, or are being set to 800m somewhere

### ISSUE THREAD

**Issue by MeridiusIX** [MeridiusIX/Modular-Encounters-Systems#75]

**Comment by Blaylock1988** [comment]
I believe this is a bug again. I'm experiencing the same thing right now. My experience is when using a random weapon replacer, the replaced weapons are set to 800m, and using a behavior with an action [SetWeaponsToMaxRange:true] seems to not have any affect.
