### ISSUE TITLE
If ignoreSafetyCheck in CustomSpawnRequest is true it causes a "Could Not Get Valid NPC Faction" error

### ISSUE THREAD

**Issue by Justforthelolz** [MeridiusIX/Modular-Encounters-Systems#78]
If ignoreSafetyCheck is true it causes the resultList in ValidNpcFactions to be returned early. The faction from factionOverride is only added to factionList at that point. The factions from factionList are only added to resultList at the end of the method.

**Comment by MeridiusIX** [comment]
Fixed in 2.0.30
