### ISSUE TITLE
"RandomSelectedIndexes" Prefab Spawning Mode does not work

### ISSUE THREAD

**Issue by vaidasmaciulis** [MeridiusIX/Modular-Encounters-Systems#91]
[PrefabSpawningMode:RandomSelectedIndexes] does not spawn prefabs.

Likely root cause:
https://github.com/MeridiusIX/Modular-Encounters-Systems/blob/2f1987b9797571094549a888a30ba1c7c282748f/Data/Scripts/ModularEncountersSystems/Spawning/SpawnGroupCollection.cs

Line 248
`if (Conditions.PrefabSpawningMode == PrefabSpawnMode.SelectedIndexes)`

should be 
`if (Conditions.PrefabSpawningMode == PrefabSpawnMode.RandomSelectedIndexes)`

**Comment by MeridiusIX** [comment]
Good catch! I'll have that fixed in the next update. Thanks!

**Comment by MeridiusIX** [comment]
Fix implemented in code, will push with update later today.

**Comment by vaidasmaciulis** [comment]
@MeridiusIX was this fixed? I don't see changes in code, and it still doe snot work for me. Is there an working example of RandomSelectedIndexes somwhere?

**Comment by MeridiusIX** [comment]
I haven't updated the repository in a while on github, but the change should be live. If its still not working, I'll have a look at it on my days off. Let me know if its still giving you a hard time by the weekend.

**Comment by MeridiusIX** [comment]
Found the issue(s). They'll be fixed in the update this weekend.
